### ISSUE TITLE
https don't work correctly

### ISSUE THREAD

**Issue by stefkey** [portachtzig/neos-piwik#10]
Hi, 

it would be nice when your package use in the tracking code the complete url, because on my system it count not all visitors. I have chance now the TrackingCode.html to:
`var u="https://{settings.host}/";` Thats count all visitors.

This `var u="//{settings.host}/";` count only a few in my environment.

**Comment by Sebobo** [comment]
Fixed in https://github.com/portachtzig/neos-piwik/commit/e93269b06fa00e6ebb7eb0b71a4b575ff4f1a78a
